#total waste generated in TMC per day
TotWaste = 211800

BioCom = 15833
PipCom = 87000
Biogas = 1749
KitBin = 7000

Waste_BioCom = BioCom 

Waste_PipCom = PipCom 

Waste_Biogas = Biogas
  
Waste_KitBin = KitBin
  
Waste_Aerobin = TotWaste - (Waste_BioCom + Waste_KitBin + Waste_Biogas + Waste_PipCom)
Waste_Aerobin 
    
PopData <- read.csv(file="C:/Users/hp/Desktop/WardPop.csv", header=TRUE, sep=",")

#TMC population
Pop = sum(PopData$Population)
Pop

#waste generated per capita per day
WasGen = Waste_Aerobin/Pop
WasGen

#waste generated by ward 1 per day
WG1 = WasGen * PopData[1,4]
WG1

#capacity of one aerobin
Cap = 160

#Number of aerobins required
m1 = WG1/Cap
m1

#number of aerobin locations required with each having
